#!/bin/sh

repo_path="${HOME}/.config"

case $BLOCK_BUTTON in
    1) python -c "import subprocess; subprocess.run('$TERMINAL', cwd='$repo_path')";;
esac

if ! git --work-tree="${repo_path}" --git-dir="${repo_path}"/.git diff-index --quiet HEAD --; then
    printf "<span color='#ff0000'>config dirty</span>"
fi
