#!/bin/sh

battery_value=$(headsetcontrol -c -b)
# Below variables provide levels over which the corresponding color will be applied
# E.g. if battery level is over 50 - the indicator is green
green_cutoff=50
yellow_cutoff=20
red_cutoff=0

case $BLOCK_BUTTON in
    1) dunstify -i audio-headset -u low -a "Headset battery" "${battery_value}%";;
    2) headsetcontrol -l 0 -s 100 && headsetcontrol -n 1 && dunstify -i audio-headset -u low -a "Headset config" "LED disabled, feedback on"
esac

span_color=""

if [ "$battery_value" -ge "$green_cutoff" ]; then
    span_color="#ffffff"
    icon=""
elif [ "$battery_value" -ge "$yellow_cutoff" ]; then
    span_color="#ffaf00"
    icon=""
elif [ "$battery_value" -ge "$red_cutoff" ]; then
    span_color="#cc0403"
    icon=""
elif [ "$battery_value" -eq -1 ]; then # At the time of writing, -1 = "Charging"
    span_color="#00ff00"
    icon=""
fi

printf "<span color='%s'>%s</span>" "$span_color" "$icon"
