#!/bin/sh
# Original author: Luke Smith
# https://github.com/LukeSmithxyz/LARBS/

pulsemixer_cmd="pulsemixer"

case $BLOCK_BUTTON in
    1) setsid -f nohup pavucontrol --class=floating_pavucontrol > /dev/null 2>&1 ;;
    2) ${pulsemixer_cmd} --toggle-mute ;;
    4) ${pulsemixer_cmd} --change-volume +5 ;;
    5) ${pulsemixer_cmd} --change-volume -5 ;;
esac

[ "$(${pulsemixer_cmd} --get-mute)" = "1" ] && printf "🔇\\n" && exit

vol=$(${pulsemixer_cmd} --get-volume | awk '{print $1}')

if [ "$vol" -gt "70" ]; then
    icon="🔊"
elif [ "$vol" -lt "30" ]; then
    icon="🔈"
else
    icon="🔉"
fi


if [ "$vol" -gt "80" ]; then
    bars="▁▃▅▇█"
elif [ "$vol" -gt "60" ]; then
    bars="▁▃▅▇ "
elif [ "$vol" -gt "40" ]; then
    bars="▁▃▅  "
elif [ "$vol" -gt "20" ]; then
    bars="▁▃   "
elif [ "$vol" -gt "0" ]; then
    bars="▁    "
else
    bars="     "
fi

printf "%s %s\n" "$icon" "${bars}"
